'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'
'     Änderungen an dieser Datei können fehlerhaftes Verhalten verursachen und gehen verloren, wenn
'     der Code wird erneut generiert. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Manage

    ''' <summary>
    ''' SuccessMessagePlaceHolder-Steuerelement
    ''' </summary>
    ''' <remarks>
    ''' Automatisch generiertes Feld.
    ''' Zum Ändern die Felddeklaration aus der Designerdatei in die CodeBehind-Datei verschieben.
    ''' </remarks>
    Protected WithEvents SuccessMessagePlaceHolder As Global.System.Web.UI.WebControls.PlaceHolder

    ''' <summary>
    ''' setPassword-Steuerelement
    ''' </summary>
    ''' <remarks>
    ''' Automatisch generiertes Feld.
    ''' Zum Ändern die Felddeklaration aus der Designerdatei in die CodeBehind-Datei verschieben.
    ''' </remarks>
    Protected WithEvents setPassword As Global.System.Web.UI.WebControls.PlaceHolder

    ''' <summary>
    ''' password-Steuerelement
    ''' </summary>
    ''' <remarks>
    ''' Automatisch generiertes Feld.
    ''' Zum Ändern die Felddeklaration aus der Designerdatei in die CodeBehind-Datei verschieben.
    ''' </remarks>
    Protected WithEvents password As Global.System.Web.UI.WebControls.TextBox

    ''' <summary>
    ''' confirmPassword-Steuerelement
    ''' </summary>
    ''' <remarks>
    ''' Automatisch generiertes Feld.
    ''' Zum Ändern die Felddeklaration aus der Designerdatei in die CodeBehind-Datei verschieben.
    ''' </remarks>
    Protected WithEvents confirmPassword As Global.System.Web.UI.WebControls.TextBox

    ''' <summary>
    ''' changePasswordHolder-Steuerelement
    ''' </summary>
    ''' <remarks>
    ''' Automatisch generiertes Feld.
    ''' Zum Ändern die Felddeklaration aus der Designerdatei in die CodeBehind-Datei verschieben.
    ''' </remarks>
    Protected WithEvents changePasswordHolder As Global.System.Web.UI.WebControls.PlaceHolder

    ''' <summary>
    ''' changePasswordUserName-Steuerelement
    ''' </summary>
    ''' <remarks>
    ''' Automatisch generiertes Feld.
    ''' Zum Ändern die Felddeklaration aus der Designerdatei in die CodeBehind-Datei verschieben.
    ''' </remarks>
    Protected WithEvents changePasswordUserName As Global.System.Web.UI.WebControls.Label

    ''' <summary>
    ''' CurrentPasswordLabel-Steuerelement
    ''' </summary>
    ''' <remarks>
    ''' Automatisch generiertes Feld.
    ''' Zum Ändern die Felddeklaration aus der Designerdatei in die CodeBehind-Datei verschieben.
    ''' </remarks>
    Protected WithEvents CurrentPasswordLabel As Global.System.Web.UI.WebControls.Label

    ''' <summary>
    ''' CurrentPassword-Steuerelement
    ''' </summary>
    ''' <remarks>
    ''' Automatisch generiertes Feld.
    ''' Zum Ändern die Felddeklaration aus der Designerdatei in die CodeBehind-Datei verschieben.
    ''' </remarks>
    Protected WithEvents CurrentPassword As Global.System.Web.UI.WebControls.TextBox

    ''' <summary>
    ''' NewPasswordLabel-Steuerelement
    ''' </summary>
    ''' <remarks>
    ''' Automatisch generiertes Feld.
    ''' Zum Ändern die Felddeklaration aus der Designerdatei in die CodeBehind-Datei verschieben.
    ''' </remarks>
    Protected WithEvents NewPasswordLabel As Global.System.Web.UI.WebControls.Label

    ''' <summary>
    ''' NewPassword-Steuerelement
    ''' </summary>
    ''' <remarks>
    ''' Automatisch generiertes Feld.
    ''' Zum Ändern die Felddeklaration aus der Designerdatei in die CodeBehind-Datei verschieben.
    ''' </remarks>
    Protected WithEvents NewPassword As Global.System.Web.UI.WebControls.TextBox

    ''' <summary>
    ''' ConfirmNewPasswordLabel-Steuerelement
    ''' </summary>
    ''' <remarks>
    ''' Automatisch generiertes Feld.
    ''' Zum Ändern die Felddeklaration aus der Designerdatei in die CodeBehind-Datei verschieben.
    ''' </remarks>
    Protected WithEvents ConfirmNewPasswordLabel As Global.System.Web.UI.WebControls.Label

    ''' <summary>
    ''' ConfirmNewPassword-Steuerelement
    ''' </summary>
    ''' <remarks>
    ''' Automatisch generiertes Feld.
    ''' Zum Ändern die Felddeklaration aus der Designerdatei in die CodeBehind-Datei verschieben.
    ''' </remarks>
    Protected WithEvents ConfirmNewPassword As Global.System.Web.UI.WebControls.TextBox
    
End Class
